package com.saicon.games.callcard.util;

public enum EventType {
    CREATE, UPDATE, DELETE, SUBMIT, COMPLETE, CANCEL,
    CALL_CARD_STATISTICS, NO_DISTINCT_CALL_CARD_TEMPLATE,
    CALL_CARD_UPLOADED, CALL_CARD_INDIRECT_ACTION;
}
